//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class gamestages {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("config", typeof(gamestagesConfig), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("group", typeof(gamestagesGroup), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gamestagesConfig {
    
    private string daysAliveChangeWhenKilledField;
    
    private string scavengerGameDifficultyBonusField;
    
    private string adventurerGameDifficultyBonusField;
    
    private string nomadGameDifficultyBonusField;
    
    private string warriorGameDifficultyBonusField;
    
    private string survivalistGameDifficultyBonusField;
    
    private string insaneGameDifficultyBonusField;
    
    private string startingWeightField;
    
    private string diminishingReturnsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string daysAliveChangeWhenKilled {
        get {
            return this.daysAliveChangeWhenKilledField;
        }
        set {
            this.daysAliveChangeWhenKilledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scavengerGameDifficultyBonus {
        get {
            return this.scavengerGameDifficultyBonusField;
        }
        set {
            this.scavengerGameDifficultyBonusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string adventurerGameDifficultyBonus {
        get {
            return this.adventurerGameDifficultyBonusField;
        }
        set {
            this.adventurerGameDifficultyBonusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nomadGameDifficultyBonus {
        get {
            return this.nomadGameDifficultyBonusField;
        }
        set {
            this.nomadGameDifficultyBonusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string warriorGameDifficultyBonus {
        get {
            return this.warriorGameDifficultyBonusField;
        }
        set {
            this.warriorGameDifficultyBonusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string survivalistGameDifficultyBonus {
        get {
            return this.survivalistGameDifficultyBonusField;
        }
        set {
            this.survivalistGameDifficultyBonusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string insaneGameDifficultyBonus {
        get {
            return this.insaneGameDifficultyBonusField;
        }
        set {
            this.insaneGameDifficultyBonusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string startingWeight {
        get {
            return this.startingWeightField;
        }
        set {
            this.startingWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string diminishingReturns {
        get {
            return this.diminishingReturnsField;
        }
        set {
            this.diminishingReturnsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gamestagesGroup {
    
    private gamestagesGroupSpawner[] spawnerField;
    
    private string nameField;
    
    private string emptyChanceField;
    
    private string decoyChanceField;
    
    private string decoy1hpChanceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("spawner", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public gamestagesGroupSpawner[] spawner {
        get {
            return this.spawnerField;
        }
        set {
            this.spawnerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string emptyChance {
        get {
            return this.emptyChanceField;
        }
        set {
            this.emptyChanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string decoyChance {
        get {
            return this.decoyChanceField;
        }
        set {
            this.decoyChanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string decoy1hpChance {
        get {
            return this.decoy1hpChanceField;
        }
        set {
            this.decoy1hpChanceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gamestagesGroupSpawner {
    
    private gamestagesGroupSpawnerGamestage[] gamestageField;
    
    private string nameField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gamestage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public gamestagesGroupSpawnerGamestage[] gamestage {
        get {
            return this.gamestageField;
        }
        set {
            this.gamestageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gamestagesGroupSpawnerGamestage {
    
    private gamestagesGroupSpawnerGamestageSpawn[] spawnField;
    
    private string stageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("spawn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public gamestagesGroupSpawnerGamestageSpawn[] spawn {
        get {
            return this.spawnField;
        }
        set {
            this.spawnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stage {
        get {
            return this.stageField;
        }
        set {
            this.stageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gamestagesGroupSpawnerGamestageSpawn {
    
    private string groupField;
    
    private string numField;
    
    private string maxAliveField;
    
    private string durationField;
    
    private string intervalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string num {
        get {
            return this.numField;
        }
        set {
            this.numField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxAlive {
        get {
            return this.maxAliveField;
        }
        set {
            this.maxAliveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string interval {
        get {
            return this.intervalField;
        }
        set {
            this.intervalField = value;
        }
    }
}
